name: Correção Monetário CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-latest
    name: Testes PHP

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo_mysql
        coverage: none

    - name: Cache Composer
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: |
          app/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('app/composer.lock') }}-${{ hashFiles('app/composer.json') }}
        restore-keys: ${{ runner.os }}-composer

    - name: composer install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
          cd app && composer install

    - name: Run PHPUnit
      run: |
          cd app && composer test
